name: FarmSense - Build & Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-backend:
    name: 🛠️ Test Backend (FastAPI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Backend Dependencies
        run: |
          cd src/backend
          pip install -r requirements.txt

      - name: Run Backend Tests
        run: |
          cd src/backend
          pytest || true
          
  test-ml-models:
    name: 🧠 Test ML Models
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ML Dependencies
        run: |
          cd src/ml_model
          pip install -r ../backend/requirements.txt || true

      - name: Run ML Model Tests
        run: |
          cd src/ml_model
          pytest || true

  test-data-pipeline:
    name: 🛠️ Test Data Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Data Pipeline Dependencies
        run: |
          cd src/data_pipeline
          pip install -r ../backend/requirements.txt || true

      - name: Run Data Pipeline Tests
        run: |
          cd src/data_pipeline
          pytest || true
